### ISSUE TITLE
skin_hvg_cut_1000.npy

### ISSUE THREAD

**Issue by Syderny** [maxpmx/HisToGene#1]
Hi there,

I notice that `skin_hvg_cut_1000.npy` is missing when I try to run the `ViT_SKIN` dataset.

The cscc dataset files have been downloaded correctly. I have tried to use the preprocess functions in `utils.py`, and scanpy package functions like `highly_variable_genes`, `filter_genes` according to the description of preprocess in the paper:
> We then select the top 1,000 highly variable genes in each tissue section and eliminate genes that are expressed in less than 1,000 spots across all tissue sections.

like this:
```python
adata = ad.concat(adata_list, merge='only')
adata.obs_names_make_unique()
adata.var_names_make_unique()
sc.pp.normalize_total(adata)
sc.pp.log1p(adata)
sc.pp.highly_variable_genes(adata, n_top_genes=1000, subset=True)
sc.pp.filter_genes(adata, min_counts=1000)
```
but the result is different from 134 genes remained according to Supplementary Note 1.

So can we have the real preprocess function that can generate `skin_hvg_cut_1000.npy`?

Thank you!

**Comment by maxpmx** [comment]
Thanks for your interest in our work. In our implementation, we select the genes that are expressed in over 1000 spots. It is different from the using `sc.pp.filter_genes(adata, min_counts=1000)`. Because it would consider the counts in each spot.

**Comment by Syderny** [comment]
> Thanks for your interest in our work. In our implementation, we select the genes that are expressed in over 1000 spots. It is different from the using `sc.pp.filter_genes(adata, min_counts=1000)`. Because it would consider the counts in each spot.

Thank you for your answer!
